POST https://node-do-zero-cct9.onrender.com/videos
Content-Type: application/json

{
    "title": "Video 01",
    "description": "Esse é o primeiro video",
    "duration": 180
}

###

POST https://node-do-zero-cct9.onrender.com/videos
Content-Type: application/json

{
    "title": "Video 02",
    "description": "Esse é o segundo video",
    "duration": 30
}

###

POST https://node-do-zero-cct9.onrender.com/videos
Content-Type: application/json

{
    "title": "Video node",
    "description": "Esse é o video com a palavra node no titulo",
    "duration": 30
}

###

GET https://node-do-zero-cct9.onrender.com/videos

###

GET https://node-do-zero-cct9.onrender.com/videos?search=node

###

PUT https://node-do-zero-cct9.onrender.com/videos/5c3e364c-2f0f-4f87-9aeb-69af34004685
Content-Type: application/json

{
    "title": "Video 02 Alterado",
    "description": "Esse é o video 02 que foi alterado",
    "duration": 60
}

###

DELETE https://node-do-zero-cct9.onrender.com/videos/b3b4790d-1511-4104-afbf-0f66a91f0101